name: Deploy Frontend Client (Next.js) CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Docker Hub에 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Next.js 빌드 시 필요한 환경 변수(API 주소 등)를 주입
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trend-chat-client:latest
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

  # CD: Kubernetes에 배포하는 작업
  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/trend-chat-client \
          trend-chat-client=doolchong/trend-chat-client:latest

      - name: Verify deployment
        run: kubectl rollout status deployment/trend-chat-client
